<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Authors>Aquila Huang</Authors>
    <Description>Mysql provider for Light.Data</Description>
    <Copyright>Copyright © 2017</Copyright>
    <PackageVersion>2.1.4.4</PackageVersion>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>LightData.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MySql.Data" Version="9.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Light.Data\Light.Data.csproj" />
  </ItemGroup>

</Project>
