//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Light.Data {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Light.Data.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Can not find alias name via specified path &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string CanNotFindAliasNameViaSpecifiedPath {
            get {
                return ResourceManager.GetString("CanNotFindAliasNameViaSpecifiedPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not find the specified field &apos;{0}&apos; in type &apos;{1}&apos; 的本地化字符串。
        /// </summary>
        internal static string CanNotFindTheSpecifiedField {
            get {
                return ResourceManager.GetString("CanNotFindTheSpecifiedField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not find specified field via path &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string CanNotFindTheSpecifiedFieldViaPath {
            get {
                return ResourceManager.GetString("CanNotFindTheSpecifiedFieldViaPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Config data type &apos;{0}&apos; field &apos;{1} is not exists 的本地化字符串。
        /// </summary>
        internal static string ConfigDataFieldIsNotExists {
            get {
                return ResourceManager.GetString("ConfigDataFieldIsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Config data type &apos;{0}&apos; field &apos;{1}&apos; value load error,reason:{2} 的本地化字符串。
        /// </summary>
        internal static string ConfigDataFieldLoadError {
            get {
                return ResourceManager.GetString("ConfigDataFieldLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Config data type &apos;{0}&apos; field &apos;{1}&apos; name is null 的本地化字符串。
        /// </summary>
        internal static string ConfigDataFieldNameIsNull {
            get {
                return ResourceManager.GetString("ConfigDataFieldNameIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Config data type &apos;{0}&apos; name is null 的本地化字符串。
        /// </summary>
        internal static string ConfigDataTypeNameIsNull {
            get {
                return ResourceManager.GetString("ConfigDataTypeNameIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The configuration has been initialized 的本地化字符串。
        /// </summary>
        internal static string ConfigurationHasBeenInitialized {
            get {
                return ResourceManager.GetString("ConfigurationHasBeenInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DataContext is not exists 的本地化字符串。
        /// </summary>
        internal static string DataContextIsNotExists {
            get {
                return ResourceManager.GetString("DataContextIsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The options of context error 的本地化字符串。
        /// </summary>
        internal static string DataContextOptionsError {
            get {
                return ResourceManager.GetString("DataContextOptionsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The define error,unsupport field type &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string DataDefineUnsupportFieldType {
            get {
                return ResourceManager.GetString("DataDefineUnsupportFieldType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data field content error 的本地化字符串。
        /// </summary>
        internal static string DataFieldContentError {
            get {
                return ResourceManager.GetString("DataFieldContentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type &apos;{0}&apos; field &apos;{1}&apos; error,unsupport field type &apos;{2}&apos; 的本地化字符串。
        /// </summary>
        internal static string DataMappingUnsupportFieldType {
            get {
                return ResourceManager.GetString("DataMappingUnsupportFieldType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type &apos;{0}&apos; field &apos;{1}&apos; error,unsupport identity field type &apos;{2}&apos; 的本地化字符串。
        /// </summary>
        internal static string DataMappingUnsupportIdentityFieldType {
            get {
                return ResourceManager.GetString("DataMappingUnsupportIdentityFieldType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The default config is not exists 的本地化字符串。
        /// </summary>
        internal static string DefaultConfigNotExists {
            get {
                return ResourceManager.GetString("DefaultConfigNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type &apos;{0}&apos; enum field &apos;{1}&apos; default value &apos;{2}&apos; error 的本地化字符串。
        /// </summary>
        internal static string EnumDefaultValueType {
            get {
                return ResourceManager.GetString("EnumDefaultValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type &apos;{0}&apos; field &apos;{1}&apos; name is invalid 的本地化字符串。
        /// </summary>
        internal static string FieldNameIsInvalid {
            get {
                return ResourceManager.GetString("FieldNameIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type &apos;{0}&apos; is not data table mapping 的本地化字符串。
        /// </summary>
        internal static string IsNotDataTableMapping {
            get {
                return ResourceManager.GetString("IsNotDataTableMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Id or Key does not allow null 的本地化字符串。
        /// </summary>
        internal static string KeyNotAllowNull {
            get {
                return ResourceManager.GetString("KeyNotAllowNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type &apos;{0}&apos; has multiple identity fields 的本地化字符串。
        /// </summary>
        internal static string MultipleIdentityField {
            get {
                return ResourceManager.GetString("MultipleIdentityField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type &apos;{0}&apos; no data entity config 的本地化字符串。
        /// </summary>
        internal static string NoDataEntityConfig {
            get {
                return ResourceManager.GetString("NoDataEntityConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type &apos;{0}&apos; no identity field 的本地化字符串。
        /// </summary>
        internal static string NoIdentityField {
            get {
                return ResourceManager.GetString("NoIdentityField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type &apos;{0}&apos; does not have a mapping field 的本地化字符串。
        /// </summary>
        internal static string NoMappingField {
            get {
                return ResourceManager.GetString("NoMappingField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type &apos;{0}&apos; does not contain non-identity key fields 的本地化字符串。
        /// </summary>
        internal static string NotContainNonIdentityKeyFields {
            get {
                return ResourceManager.GetString("NotContainNonIdentityKeyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type &apos;{0}&apos; does not contain non-primary key fields 的本地化字符串。
        /// </summary>
        internal static string NotContainNonPrimaryKeyFields {
            get {
                return ResourceManager.GetString("NotContainNonPrimaryKeyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type &apos;{0}&apos; does not contain primary key fields 的本地化字符串。
        /// </summary>
        internal static string NotContainPrimaryKeyFields {
            get {
                return ResourceManager.GetString("NotContainPrimaryKeyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type &apos;{0}&apos; primary keys is not match 的本地化字符串。
        /// </summary>
        internal static string NotMatchPrimaryKeyField {
            get {
                return ResourceManager.GetString("NotMatchPrimaryKeyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parse &apos;{0}&apos; expression &apos;{1}&apos; error,message:{2} 的本地化字符串。
        /// </summary>
        internal static string ParseExpressionError {
            get {
                return ResourceManager.GetString("ParseExpressionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specific primary key data does not exists 的本地化字符串。
        /// </summary>
        internal static string PrimaryKeyDataNotExists {
            get {
                return ResourceManager.GetString("PrimaryKeyDataNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type &apos;{0}&apos; relation field &apos;{1}&apos; error 的本地化字符串。
        /// </summary>
        internal static string RelationFieldError {
            get {
                return ResourceManager.GetString("RelationFieldError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type &apos;{0}&apos; relation field &apos;{1}&apos; key not match 的本地化字符串。
        /// </summary>
        internal static string RelationFieldKeyNotMatch {
            get {
                return ResourceManager.GetString("RelationFieldKeyNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The select fields count not equid the insert field count 的本地化字符串。
        /// </summary>
        internal static string SelectFieldsCountNotEquidInsertFieldCount {
            get {
                return ResourceManager.GetString("SelectFieldsCountNotEquidInsertFieldCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified config &apos;{0}&apos; is not exists 的本地化字符串。
        /// </summary>
        internal static string SpecifiedConfigNotExists {
            get {
                return ResourceManager.GetString("SpecifiedConfigNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The TransactionScope Has Been Created 的本地化字符串。
        /// </summary>
        internal static string TransactionScopeHasBeenCreated {
            get {
                return ResourceManager.GetString("TransactionScopeHasBeenCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type {0} is not database type 的本地化字符串。
        /// </summary>
        internal static string TypeIsNotDatabaseType {
            get {
                return ResourceManager.GetString("TypeIsNotDatabaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unsupport predicate &apos;{0}&apos; in &apos;{1}&apos; field expression 的本地化字符串。
        /// </summary>
        internal static string UnsupportPredicate {
            get {
                return ResourceManager.GetString("UnsupportPredicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type &apos;{0}&apos; update field &apos;{1}&apos; is primary key 的本地化字符串。
        /// </summary>
        internal static string UpdateFieldIsPrimaryKeyField {
            get {
                return ResourceManager.GetString("UpdateFieldIsPrimaryKeyField", resourceCulture);
            }
        }
    }
}
