//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Light.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Light.Data.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not find alias name via specified path &apos;{0}&apos;.
        /// </summary>
        internal static string CanNotFindAliasNameViaSpecifiedPath {
            get {
                return ResourceManager.GetString("CanNotFindAliasNameViaSpecifiedPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not find the specified field &apos;{0}&apos; in type &apos;{1}&apos;.
        /// </summary>
        internal static string CanNotFindTheSpecifiedField {
            get {
                return ResourceManager.GetString("CanNotFindTheSpecifiedField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not find specified field via path &apos;{0}&apos;.
        /// </summary>
        internal static string CanNotFindTheSpecifiedFieldViaPath {
            get {
                return ResourceManager.GetString("CanNotFindTheSpecifiedFieldViaPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config data type &apos;{0}&apos; field &apos;{1} is not exists.
        /// </summary>
        internal static string ConfigDataFieldIsNotExists {
            get {
                return ResourceManager.GetString("ConfigDataFieldIsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config data type &apos;{0}&apos; field &apos;{1}&apos; value load error,reason:{2}.
        /// </summary>
        internal static string ConfigDataFieldLoadError {
            get {
                return ResourceManager.GetString("ConfigDataFieldLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config data type &apos;{0}&apos; field &apos;{1}&apos; name is null.
        /// </summary>
        internal static string ConfigDataFieldNameIsNull {
            get {
                return ResourceManager.GetString("ConfigDataFieldNameIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config data type &apos;{0}&apos; name is null.
        /// </summary>
        internal static string ConfigDataTypeNameIsNull {
            get {
                return ResourceManager.GetString("ConfigDataTypeNameIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration has been initialized.
        /// </summary>
        internal static string ConfigurationHasBeenInitialized {
            get {
                return ResourceManager.GetString("ConfigurationHasBeenInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataContext is not exists.
        /// </summary>
        internal static string DataContextIsNotExists {
            get {
                return ResourceManager.GetString("DataContextIsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The options of context error.
        /// </summary>
        internal static string DataContextOptionsError {
            get {
                return ResourceManager.GetString("DataContextOptionsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The define error,unsupport field type &apos;{0}&apos;.
        /// </summary>
        internal static string DataDefineUnsupportFieldType {
            get {
                return ResourceManager.GetString("DataDefineUnsupportFieldType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data field content error.
        /// </summary>
        internal static string DataFieldContentError {
            get {
                return ResourceManager.GetString("DataFieldContentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; field &apos;{1}&apos; error,unsupport field type &apos;{2}&apos;.
        /// </summary>
        internal static string DataMappingUnsupportFieldType {
            get {
                return ResourceManager.GetString("DataMappingUnsupportFieldType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; field &apos;{1}&apos; error,unsupport identity field type &apos;{2}&apos;.
        /// </summary>
        internal static string DataMappingUnsupportIdentityFieldType {
            get {
                return ResourceManager.GetString("DataMappingUnsupportIdentityFieldType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default config is not exists.
        /// </summary>
        internal static string DefaultConfigNotExists {
            get {
                return ResourceManager.GetString("DefaultConfigNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; enum field &apos;{1}&apos; default value &apos;{2}&apos; error.
        /// </summary>
        internal static string EnumDefaultValueType {
            get {
                return ResourceManager.GetString("EnumDefaultValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; field &apos;{1}&apos; name is invalid.
        /// </summary>
        internal static string FieldNameIsInvalid {
            get {
                return ResourceManager.GetString("FieldNameIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FunctionControl error.
        /// </summary>
        internal static string FunctionControlError {
            get {
                return ResourceManager.GetString("FunctionControlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; is not data table mapping.
        /// </summary>
        internal static string IsNotDataTableMapping {
            get {
                return ResourceManager.GetString("IsNotDataTableMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Id or Key does not allow null.
        /// </summary>
        internal static string KeyNotAllowNull {
            get {
                return ResourceManager.GetString("KeyNotAllowNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; has multiple identity fields.
        /// </summary>
        internal static string MultipleIdentityField {
            get {
                return ResourceManager.GetString("MultipleIdentityField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; no data entity config.
        /// </summary>
        internal static string NoDataEntityConfig {
            get {
                return ResourceManager.GetString("NoDataEntityConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; no identity field.
        /// </summary>
        internal static string NoIdentityField {
            get {
                return ResourceManager.GetString("NoIdentityField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; does not have a mapping field.
        /// </summary>
        internal static string NoMappingField {
            get {
                return ResourceManager.GetString("NoMappingField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; does not contain non-identity key fields.
        /// </summary>
        internal static string NotContainNonIdentityKeyFields {
            get {
                return ResourceManager.GetString("NotContainNonIdentityKeyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; does not contain non-primary key fields.
        /// </summary>
        internal static string NotContainNonPrimaryKeyFields {
            get {
                return ResourceManager.GetString("NotContainNonPrimaryKeyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; does not contain primary key fields.
        /// </summary>
        internal static string NotContainPrimaryKeyFields {
            get {
                return ResourceManager.GetString("NotContainPrimaryKeyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not &quot;FunctionControl&quot; type.
        /// </summary>
        internal static string NotFunctionControlType {
            get {
                return ResourceManager.GetString("NotFunctionControlType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; primary keys is not match.
        /// </summary>
        internal static string NotMatchPrimaryKeyField {
            get {
                return ResourceManager.GetString("NotMatchPrimaryKeyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output parameter not support object type.
        /// </summary>
        internal static string OutputParameterNotSupportObjectType {
            get {
                return ResourceManager.GetString("OutputParameterNotSupportObjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parse &apos;{0}&apos; expression &apos;{1}&apos; error,message:{2}.
        /// </summary>
        internal static string ParseExpressionError {
            get {
                return ResourceManager.GetString("ParseExpressionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specific primary key data does not exists.
        /// </summary>
        internal static string PrimaryKeyDataNotExists {
            get {
                return ResourceManager.GetString("PrimaryKeyDataNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; relation field &apos;{1}&apos; error.
        /// </summary>
        internal static string RelationFieldError {
            get {
                return ResourceManager.GetString("RelationFieldError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; relation field &apos;{1}&apos; key not match.
        /// </summary>
        internal static string RelationFieldKeyNotMatch {
            get {
                return ResourceManager.GetString("RelationFieldKeyNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The select fields count not equid the insert field count.
        /// </summary>
        internal static string SelectFieldsCountNotEquidInsertFieldCount {
            get {
                return ResourceManager.GetString("SelectFieldsCountNotEquidInsertFieldCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified config &apos;{0}&apos; is not exists.
        /// </summary>
        internal static string SpecifiedConfigNotExists {
            get {
                return ResourceManager.GetString("SpecifiedConfigNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transaction has begun.
        /// </summary>
        internal static string TransactionHasBegun {
            get {
                return ResourceManager.GetString("TransactionHasBegun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transaction has closed.
        /// </summary>
        internal static string TransactionHasClosed {
            get {
                return ResourceManager.GetString("TransactionHasClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transaction not begin.
        /// </summary>
        internal static string TransactionNotBegin {
            get {
                return ResourceManager.GetString("TransactionNotBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} is not database type.
        /// </summary>
        internal static string TypeIsNotDatabaseType {
            get {
                return ResourceManager.GetString("TypeIsNotDatabaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupport predicate &apos;{0}&apos; in &apos;{1}&apos; field expression.
        /// </summary>
        internal static string UnsupportPredicate {
            get {
                return ResourceManager.GetString("UnsupportPredicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; update field &apos;{1}&apos; is primary key.
        /// </summary>
        internal static string UpdateFieldIsPrimaryKeyField {
            get {
                return ResourceManager.GetString("UpdateFieldIsPrimaryKeyField", resourceCulture);
            }
        }
    }
}
