//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Light.Data {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Light.Data.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string NoMappingField {
            get {
                return ResourceManager.GetString("NoMappingField", resourceCulture);
            }
        }
        
        internal static string ConfigDataFieldIsNotExists {
            get {
                return ResourceManager.GetString("ConfigDataFieldIsNotExists", resourceCulture);
            }
        }
        
        internal static string ConfigDataFieldNameIsNull {
            get {
                return ResourceManager.GetString("ConfigDataFieldNameIsNull", resourceCulture);
            }
        }
        
        internal static string ConfigDataFieldLoadError {
            get {
                return ResourceManager.GetString("ConfigDataFieldLoadError", resourceCulture);
            }
        }
        
        internal static string ConfigDataTypeNameIsNull {
            get {
                return ResourceManager.GetString("ConfigDataTypeNameIsNull", resourceCulture);
            }
        }
        
        internal static string DataContextIsNotExists {
            get {
                return ResourceManager.GetString("DataContextIsNotExists", resourceCulture);
            }
        }
        
        internal static string MultipleIdentityField {
            get {
                return ResourceManager.GetString("MultipleIdentityField", resourceCulture);
            }
        }
        
        internal static string NoIdentityField {
            get {
                return ResourceManager.GetString("NoIdentityField", resourceCulture);
            }
        }
        
        internal static string FieldNameIsInvalid {
            get {
                return ResourceManager.GetString("FieldNameIsInvalid", resourceCulture);
            }
        }
        
        internal static string IsNotDataTableMapping {
            get {
                return ResourceManager.GetString("IsNotDataTableMapping", resourceCulture);
            }
        }
        
        internal static string NotMatchPrimaryKeyField {
            get {
                return ResourceManager.GetString("NotMatchPrimaryKeyField", resourceCulture);
            }
        }
        
        internal static string DataMappingUnsupportFieldType {
            get {
                return ResourceManager.GetString("DataMappingUnsupportFieldType", resourceCulture);
            }
        }
        
        internal static string DataDefineUnsupportFieldType {
            get {
                return ResourceManager.GetString("DataDefineUnsupportFieldType", resourceCulture);
            }
        }
        
        internal static string DataMappingUnsupportIdentityFieldType {
            get {
                return ResourceManager.GetString("DataMappingUnsupportIdentityFieldType", resourceCulture);
            }
        }
        
        internal static string NotContainNonPrimaryKeyFields {
            get {
                return ResourceManager.GetString("NotContainNonPrimaryKeyFields", resourceCulture);
            }
        }
        
        internal static string UpdateFieldIsPrimaryKeyField {
            get {
                return ResourceManager.GetString("UpdateFieldIsPrimaryKeyField", resourceCulture);
            }
        }
        
        internal static string CanNotFindTheSpecifiedField {
            get {
                return ResourceManager.GetString("CanNotFindTheSpecifiedField", resourceCulture);
            }
        }
        
        internal static string TypeIsNotDatabaseType {
            get {
                return ResourceManager.GetString("TypeIsNotDatabaseType", resourceCulture);
            }
        }
        
        internal static string NotContainPrimaryKeyFields {
            get {
                return ResourceManager.GetString("NotContainPrimaryKeyFields", resourceCulture);
            }
        }
        
        internal static string SelectFieldsCountNotEquidInsertFieldCount {
            get {
                return ResourceManager.GetString("SelectFieldsCountNotEquidInsertFieldCount", resourceCulture);
            }
        }
        
        internal static string SpecifiedConfigNotExists {
            get {
                return ResourceManager.GetString("SpecifiedConfigNotExists", resourceCulture);
            }
        }
        
        internal static string NoDataEntityConfig {
            get {
                return ResourceManager.GetString("NoDataEntityConfig", resourceCulture);
            }
        }
        
        internal static string NotContainNonIdentityKeyFields {
            get {
                return ResourceManager.GetString("NotContainNonIdentityKeyFields", resourceCulture);
            }
        }
        
        internal static string UnsupportPredicate {
            get {
                return ResourceManager.GetString("UnsupportPredicate", resourceCulture);
            }
        }
        
        internal static string DataFieldContentError {
            get {
                return ResourceManager.GetString("DataFieldContentError", resourceCulture);
            }
        }
        
        internal static string CanNotFindAliasNameViaSpecifiedPath {
            get {
                return ResourceManager.GetString("CanNotFindAliasNameViaSpecifiedPath", resourceCulture);
            }
        }
        
        internal static string RelationFieldError {
            get {
                return ResourceManager.GetString("RelationFieldError", resourceCulture);
            }
        }
        
        internal static string RelationFieldKeyNotMatch {
            get {
                return ResourceManager.GetString("RelationFieldKeyNotMatch", resourceCulture);
            }
        }
        
        internal static string CanNotFindTheSpecifiedFieldViaPath {
            get {
                return ResourceManager.GetString("CanNotFindTheSpecifiedFieldViaPath", resourceCulture);
            }
        }
        
        internal static string ParseExpressionError {
            get {
                return ResourceManager.GetString("ParseExpressionError", resourceCulture);
            }
        }
        
        internal static string EnumDefaultValueType {
            get {
                return ResourceManager.GetString("EnumDefaultValueType", resourceCulture);
            }
        }
        
        internal static string ConfigurationHasBeenInitialized {
            get {
                return ResourceManager.GetString("ConfigurationHasBeenInitialized", resourceCulture);
            }
        }
        
        internal static string DataContextOptionsError {
            get {
                return ResourceManager.GetString("DataContextOptionsError", resourceCulture);
            }
        }
        
        internal static string DefaultConfigNotExists {
            get {
                return ResourceManager.GetString("DefaultConfigNotExists", resourceCulture);
            }
        }
        
        internal static string PrimaryKeyDataNotExists {
            get {
                return ResourceManager.GetString("PrimaryKeyDataNotExists", resourceCulture);
            }
        }
        
        internal static string KeyNotAllowNull {
            get {
                return ResourceManager.GetString("KeyNotAllowNull", resourceCulture);
            }
        }
        
        internal static string TransactionHasBegun {
            get {
                return ResourceManager.GetString("TransactionHasBegun", resourceCulture);
            }
        }
        
        internal static string TransactionNotBegin {
            get {
                return ResourceManager.GetString("TransactionNotBegin", resourceCulture);
            }
        }
        
        internal static string TransactionHasClosed {
            get {
                return ResourceManager.GetString("TransactionHasClosed", resourceCulture);
            }
        }
        
        internal static string OutputParameterNotSupportObjectType {
            get {
                return ResourceManager.GetString("OutputParameterNotSupportObjectType", resourceCulture);
            }
        }
        
        internal static string FunctionControlError {
            get {
                return ResourceManager.GetString("FunctionControlError", resourceCulture);
            }
        }
        
        internal static string NotFunctionControlType {
            get {
                return ResourceManager.GetString("NotFunctionControlType", resourceCulture);
            }
        }
        
        internal static string BatchInsertIdentityError {
            get {
                return ResourceManager.GetString("BatchInsertIdentityError", resourceCulture);
            }
        }
    }
}
